### ISSUE TITLE
all tags flash instead of the specified ones

### ISSUE THREAD

**Issue by LaFesta1749** [NotIntense/RainbowTagsLabAPI#2]
```
group_specific_sequences: true
# Tags Configuration
color_interval: 0.100000001
ranks_with_r_tags:
- owner
sequences:
- red
- orange
- yellow
- green
- blue_green
- magenta
- silver
- crimson
group_sequences:
  owner:
  - red
  - orange
  - yellow
  - green
  - blue_green
  - magenta
  - silver
  - crimson
  moderatorzz:
  - red
  - orange
  - yellow
  - green
  - blue_green
  - magenta
  - silver
  - crimson
  adminzz:
  - red
  - orange
  - yellow
  - green
  - blue_green
  - magenta
  - silver
  - crimson

```

I think it's supposed only for "owner" roles to flash but instead all of them flash - moderators, junior_admins, etc...

Using [v1.0.1](https://github.com/NotIntense/RainbowTagsLabAPI/tree/v1.0.1)

@NotIntense
